cmake_minimum_required(VERSION 3.22.1)
project(omni_fingerprint LANGUAGES C CXX)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(FFT_LIB kissfft CACHE STRING "" FORCE)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(KISSFFT_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/vendor/chromaprint-1.5.1/src/3rdparty/kissfft CACHE PATH "Vendored KissFFT" FORCE)
add_subdirectory(vendor/chromaprint-1.5.1)
add_library(omni_fingerprint SHARED fingerprint.cpp)
target_include_directories(omni_fingerprint PRIVATE vendor/chromaprint-1.5.1/src)
target_link_libraries(omni_fingerprint chromaprint)
