<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows10.0.19041.0</TargetFramework><UseWPF>true</UseWPF><StartupObject>Omni.Smoke.Program</StartupObject></PropertyGroup><ItemGroup><ProjectReference Include="../../src/Windows/Windows.csproj" /></ItemGroup></Project>
