using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Omni.Core;
using static Omni.Windows.UiKit;
namespace Omni.Windows;
public sealed class LibraryView:UserControl
{
    readonly Window owner;readonly Downloader engine;readonly Store store;readonly bool tags;
    readonly HashSet<string> checkedIds=[];DownloadJob[] all=[],filtered=[];int page;string signature="";
    readonly DataGrid table=new(){AutoGenerateColumns=false,IsReadOnly=false,SelectionMode=DataGridSelectionMode.Single,SelectionUnit=DataGridSelectionUnit.FullRow,RowHeight=72};
    readonly TextBox search=new(){MinWidth=180};readonly ComboBox formats=new(){MinWidth=110},dates=new(){MinWidth=115},sort=new(){MinWidth=110};
    readonly StackPanel details=new(),summary=new(){Orientation=Orientation.Horizontal},pager=new(){Orientation=Orientation.Horizontal};readonly TextBlock status=Text("");readonly Button remove,edit;readonly CheckBox selectAll=new();
    public LibraryView(Window owner,Downloader engine,Store store,bool tags=false)
    {
        this.owner=owner;this.engine=engine;this.store=store;this.tags=tags;Resources=owner.Resources;var root=new Grid();root.ColumnDefinitions.Add(new ColumnDefinition());root.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(350)});
        var left=new DockPanel{Margin=new Thickness(16)};var heading=Text(tags?T("標籤編輯","Tag editor"):T("已下載","Downloaded"),28);DockPanel.SetDock(heading,Dock.Top);left.Children.Add(heading);
        var description=Text(T("管理所有已下載嘅影片與音訊","Manage your downloaded videos and audio"),14);description.Margin=new Thickness(0,5,0,12);DockPanel.SetDock(description,Dock.Top);left.Children.Add(description);
        var filters=new Grid();for(int i=0;i<4;i++)filters.ColumnDefinitions.Add(new ColumnDefinition{Width=i==0?new GridLength(1,GridUnitType.Star):GridLength.Auto});
        var controls=new FrameworkElement[]{search,formats,dates,sort};for(int i=0;i<controls.Length;i++){Grid.SetColumn(controls[i],i);filters.Children.Add(controls[i]);}search.TextChanged+=(_,_)=>Filter();System.Windows.Automation.AutomationProperties.SetName(search,T("搜尋標題、歌手、專輯、網址、檔名","Search title, artist, album, URL or filename"));
        formats.ItemsSource=tags?new[]{"MP3"}:new[]{T("全部格式","All formats"),"MP4","MKV","WebM","MP3","M4A","FLAC","WAV"};dates.ItemsSource=new[]{T("所有日期","Any date"),T("最近 7 日","Last 7 days"),T("最近 30 日","Last 30 days")};sort.ItemsSource=new[]{T("最新完成","Newest"),T("最早完成","Oldest"),T("檔名 A–Z","Name A–Z"),T("大小由大至細","Largest first")};formats.SelectedIndex=dates.SelectedIndex=sort.SelectedIndex=0;formats.SelectionChanged+=(_,_)=>Filter();dates.SelectionChanged+=(_,_)=>Filter();sort.SelectionChanged+=(_,_)=>Filter();DockPanel.SetDock(filters,Dock.Top);left.Children.Add(filters);
        DockPanel.SetDock(summary,Dock.Top);left.Children.Add(summary);var actions=new WrapPanel();selectAll.Content=T("全選篩選結果","Select all results");selectAll.Click+=(_,_)=>{foreach(var j in filtered){if(selectAll.IsChecked==true)checkedIds.Add(j.Id);else checkedIds.Remove(j.Id);}Rows();};actions.Children.Add(selectAll);
        remove=Button(T("移除所選","Remove selected"),async()=>await Delete(Selected()));actions.Children.Add(remove);actions.Children.Add(Button(T("清除紀錄","Clear history"),async()=>{var ids=filtered.Select(j=>j.Id).ToArray();if(ids.Length>0&&await new ConfirmWindow(owner,T("清除紀錄","Clear history"),T($"清除篩選出嘅 {ids.Length} 筆紀錄？實體檔案會保留。",$"Clear {ids.Length} matching records? Files will be kept."),T("清除紀錄","Clear records")).Ask()){store.ClearHistory(ids);Refresh(true);}}));
        edit=Button(T("MP3 標籤編輯","Edit MP3 tags"),EditTags);actions.Children.Add(edit);DockPanel.SetDock(actions,Dock.Top);left.Children.Add(actions);DockPanel.SetDock(status,Dock.Bottom);left.Children.Add(status);DockPanel.SetDock(pager,Dock.Bottom);left.Children.Add(pager);left.Children.Add(table);root.Children.Add(Card(left,0));
        var detailScroll=new ScrollViewer{Content=details,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled,Padding=new Thickness(18,14,18,18)};var card=Card(detailScroll,0);Grid.SetColumn(card,1);detailScroll.Resources[typeof(System.Windows.Controls.Primitives.ScrollBar)]=owner.FindResource("SlimScrollBar");root.Children.Add(card);Content=root;
        var checkbox=new FrameworkElementFactory(typeof(CheckBox));checkbox.SetBinding(System.Windows.Controls.Primitives.ToggleButton.IsCheckedProperty,new Binding("Checked"){Mode=BindingMode.TwoWay,UpdateSourceTrigger=UpdateSourceTrigger.PropertyChanged});table.Columns.Add(new DataGridTemplateColumn{Width=38,CellTemplate=new DataTemplate{VisualTree=checkbox}});
        var row=new FrameworkElementFactory(typeof(DockPanel));var image=new FrameworkElementFactory(typeof(Image));image.SetValue(FrameworkElement.WidthProperty,64d);image.SetValue(FrameworkElement.HeightProperty,44d);image.SetValue(FrameworkElement.MarginProperty,new Thickness(0,0,12,0));image.SetValue(Image.StretchProperty,Stretch.Uniform);image.SetBinding(Image.SourceProperty,new Binding("Job.Thumbnail"));row.AppendChild(image);var title=new FrameworkElementFactory(typeof(TextBlock));title.SetBinding(TextBlock.TextProperty,new Binding("Job.Title"));title.SetValue(TextBlock.TextTrimmingProperty,TextTrimming.CharacterEllipsis);title.SetValue(FrameworkElement.VerticalAlignmentProperty,VerticalAlignment.Center);row.AppendChild(title);table.Columns.Add(new DataGridTemplateColumn{Header=T("標題","Title"),Width=new DataGridLength(1,DataGridLengthUnitType.Star),MinWidth=175,CellTemplate=new DataTemplate{VisualTree=row},IsReadOnly=true});
        Col(T("格式","Format"),"Job.Format",60);Col(T("畫質／音質","Quality"),"Job.Quality",90);Col(T("大小","Size"),"Job.SizeText",85);Col(T("完成時間","Finished"),"Job.CompletedText",160);Col(T("狀態","Status"),"Status",100);
        var more=new FrameworkElementFactory(typeof(Button));more.SetValue(ContentControl.ContentProperty,"⋯");more.SetValue(Control.FontSizeProperty,22d);more.SetValue(Control.PaddingProperty,new Thickness(0));more.SetValue(FrameworkElement.MarginProperty,new Thickness(0));more.AddHandler(System.Windows.Controls.Primitives.ButtonBase.ClickEvent,new RoutedEventHandler(More));table.Columns.Add(new DataGridTemplateColumn{Header="",Width=42,CellTemplate=new DataTemplate{VisualTree=more}});
        table.SelectionChanged+=(_,_)=>{if(table.SelectedItem is LibraryRow r)ShowDetails(r.Job);};table.MouseDoubleClick+=(_,e)=>{if(ItemsControl.ContainerFromElement(table,e.OriginalSource as DependencyObject) is DataGridRow&&table.SelectedItem is LibraryRow r)Play(r.Job);};Refresh(true);
    }
    void Col(string label,string binding,int width){var column=new DataGridTextColumn{Header=label,Binding=new Binding(binding),Width=width,IsReadOnly=true};if(binding=="Status"){var style=new Style(typeof(TextBlock));style.Setters.Add(new Setter(TextBlock.ForegroundProperty,Brush("#29C978")));var missing=new DataTrigger{Binding=new Binding("Exists"),Value=false};missing.Setters.Add(new Setter(TextBlock.ForegroundProperty,Brush("#EB6464")));style.Triggers.Add(missing);column.ElementStyle=style;}table.Columns.Add(column);}
    public void Refresh(bool force=false){var records=store.Load(true).Where(j=>j.State==JobState.Completed&&!j.IsGroupRoot&&(!tags||j.Extension=="mp3")).ToArray();var sig=string.Join('|',records.Select(j=>j.Id+j.Title+j.FilePath+j.Format+j.CompletedText));if(!force&&sig==signature)return;signature=sig;all=records;checkedIds.IntersectWith(all.Select(j=>j.Id));Filter();}
    void Filter(){if(formats.SelectedIndex<0||dates.SelectedIndex<0||sort.SelectedIndex<0)return;var f=tags?"mp3":formats.SelectedIndex==0?"":formats.SelectedItem.ToString()!.ToLowerInvariant();var since=DateTimeOffset.Now.AddDays(dates.SelectedIndex==1?-7:-30);var source=all.Where(j=>HistorySearch.Matches(j,search.Text)&&(f==""||j.Extension==f)&&(dates.SelectedIndex==0||j.CompletedAt>=since));filtered=(sort.SelectedIndex switch{1=>source.OrderBy(j=>j.CompletedAt),2=>source.OrderBy(j=>Path.GetFileName(j.FilePath),StringComparer.CurrentCultureIgnoreCase),3=>source.OrderByDescending(j=>j.TotalBytes),_=>source.OrderByDescending(j=>j.CompletedAt)}).ToArray();page=0;Rows();}
    void Rows(){var previous=(table.SelectedItem as LibraryRow)?.Job.Id;table.ItemsSource=filtered.Skip(page*20).Take(20).Select(j=>new LibraryRow(j,checkedIds.Contains(j.Id),v=>{if(v)checkedIds.Add(j.Id);else checkedIds.Remove(j.Id);Buttons();})).ToArray();if(previous is not null)table.SelectedItem=table.Items.Cast<LibraryRow>().FirstOrDefault(r=>r.Job.Id==previous);Buttons();summary.Children.Clear();foreach(var pair in new[]{(T("已完成","Completed"),all.Length.ToString()),(T("影片","Video"),all.Count(j=>j.Mode==DownloadMode.Mp4).ToString()),(T("音訊","Audio"),all.Count(j=>j.Mode==DownloadMode.Mp3).ToString()),(T("檔案總大小","File sizes"),$"{all.Sum(j=>j.TotalBytes??0)/1_000_000_000.0:F2} GB")}){var s=new StackPanel{MinWidth=90};s.Children.Add(Text(pair.Item1,12));s.Children.Add(Text(pair.Item2,24));summary.Children.Add(Card(s,10));}pager.Children.Clear();pager.Children.Add(Text(T($"第 {(filtered.Length==0?0:page*20+1)}–{Math.Min((page+1)*20,filtered.Length)} 項，共 {filtered.Length} 項",$"{(filtered.Length==0?0:page*20+1)}–{Math.Min((page+1)*20,filtered.Length)} of {filtered.Length}"),13));var back=Button("‹",()=>{page--;Rows();});back.IsEnabled=page>0;pager.Children.Add(back);pager.Children.Add(Text((page+1).ToString()));var next=Button("›",()=>{page++;Rows();});next.IsEnabled=(page+1)*20<filtered.Length;pager.Children.Add(next);if(details.Children.Count==0)details.Children.Add(Text(T("選取檔案查看詳情","Select a file to view details"),19));}
    void Buttons(){remove.IsEnabled=checkedIds.Count>0;edit.IsEnabled=Selected().Any(j=>j.Extension=="mp3");selectAll.IsChecked=filtered.Length>0&&filtered.All(j=>checkedIds.Contains(j.Id));}
    DownloadJob[] Selected()=>all.Where(j=>checkedIds.Contains(j.Id)).ToArray();
    void ShowDetails(DownloadJob j){details.Children.Clear();details.Children.Add(Text(T("檔案詳情","File details"),23));try{if(j.Thumbnail is not null)details.Children.Add(new Image{Source=new BitmapImage(new Uri(j.Thumbnail)),Stretch=Stretch.Uniform,Height=185,Margin=new Thickness(0,18,0,12)});}catch{}details.Children.Add(Text(Path.GetFileName(j.FilePath)??j.Title,20));foreach(var pair in new[]{(T("格式","Format"),j.Format),(T("畫質／音質","Quality"),j.Quality),(T("大小","Size"),j.SizeText),(T("完成時間","Finished"),j.CompletedText),(T("狀態","Status"),File.Exists(j.FilePath)?T("✓ 已完成","✓ Completed"):T("檔案不存在","File missing")),(T("歌手","Artist"),j.Artist),(T("專輯","Album"),j.Album)}){var t=Text(pair.Item1+"　"+pair.Item2);t.Margin=new Thickness(0,9,0,2);details.Children.Add(t);}details.Children.Add(new TextBox{Text=j.FilePath??"",IsReadOnly=true,TextWrapping=TextWrapping.Wrap});details.Children.Add(Button(T("▶ 播放","▶ Play"),()=>Play(j),true));details.Children.Add(Button(T("開啟檔案位置","Show in folder"),()=>Run(()=>ShellFiles.Select(j.FilePath!))));details.Children.Add(Button(T("重新命名","Rename"),async()=>await Rename(j)));details.Children.Add(Button(T("刪除檔案","Delete file"),async()=>await Delete([j])));}
    void More(object sender,RoutedEventArgs e){if(sender is not Button{DataContext:LibraryRow r}button)return;var menu=new ContextMenu{Resources=owner.Resources,Background=(Brush)owner.FindResource("Raised"),Foreground=owner.Foreground};void Add(string label,Action action){var m=new MenuItem{Header=label,Padding=new Thickness(16,8,16,8)};m.Click+=(_,_)=>action();menu.Items.Add(m);}Add(T("播放","Play"),()=>Play(r.Job));Add(T("開啟檔案位置","Show in folder"),()=>Run(()=>ShellFiles.Select(r.Job.FilePath!)));Add(T("重新命名","Rename"),async()=>await Rename(r.Job));Add(T("重新下載","Download again"),async()=>{try{await engine.Accept(new(Guid.NewGuid().ToString(),r.Job.Url,r.Job.Mode==DownloadMode.Mp3?"mp3":"mp4",null,r.Job.Extension));status.Text=T("已加入下载佇列；私人內容需要由擴充功能重新傳送登入憑證。","Queued; private content needs fresh credentials from the extension.");}catch(Exception ex){status.Text=ex.Message;}});Add(T("查看檔案資訊","File information"),()=>ShowDetails(r.Job));Add(T("刪除檔案","Delete file"),async()=>await Delete([r.Job]));button.ContextMenu=menu;menu.PlacementTarget=button;menu.IsOpen=true;}
    async Task Delete(DownloadJob[] selection){var snapshot=selection.Where(j=>j.FilePath is not null).GroupBy(j=>j.FilePath,StringComparer.OrdinalIgnoreCase).Select(g=>g.First()).ToArray();if(snapshot.Length==0)return;if(owner.OwnedWindows.OfType<TagWindow>().Any()){status.Text=T("請先關閉標籤編輯","Close the tag editor first");return;}if(!await new ConfirmWindow(owner,T("刪除所選檔案","Delete selected files"),T($"將 {snapshot.Length} 個檔案移至資源回收筒，並清除對應紀錄？",$"Move {snapshot.Length} files to Recycle Bin and remove their records?"),T("移到資源回收筒","Move to Recycle Bin")).Ask())return;int failed=0;foreach(var j in snapshot)try{LibraryActions.DeleteFile(store,j.Id,j.FilePath!,ShellFiles.Recycle);}catch{failed++;}checkedIds.Clear();details.Children.Clear();Refresh(true);status.Text=T($"已處理 {snapshot.Length-failed} 個檔案"+(failed>0?$"；{failed} 個失敗，紀錄保留。":""),$"Removed {snapshot.Length-failed} files"+(failed>0?$"; {failed} failed, records kept.":""));}
    async Task Rename(DownloadJob j){var dialog=Dialogs.Basic(owner,T("重新命名檔案","Rename file"),490,275);var panel=new StackPanel{Margin=new Thickness(22)};panel.Children.Add(Text(T("只變更實體檔名；音訊標籤請用 MP3 標籤編輯。","Changes the filename only. Use the tag editor for MP3 metadata."),13));var field=new TextBox{Text=Path.GetFileNameWithoutExtension(j.FilePath)};panel.Children.Add(field);var warning=Text("");warning.Foreground=Brush("#EB6464");panel.Children.Add(warning);var completion=new TaskCompletionSource<bool>();var save=Button(T("儲存","Save"),async()=>{try{await engine.RenameDownloaded(j.Id,field.Text??"");completion.TrySetResult(true);dialog.Close();Refresh(true);}catch(Exception ex){warning.Text=ex.Message;}});panel.Children.Add(save);field.TextChanged+=(_,_)=>{warning.Text=Omni.Core.Validation.TitleError(field.Text??"")??"";save.IsEnabled=!string.IsNullOrEmpty(field.Text)&&warning.Text.Length==0;};dialog.Content=panel;dialog.Closed+=(_,_)=>completion.TrySetResult(false);dialog.Show();await completion.Task;}
    void EditTags(){var selection=Selected().Where(j=>j.Extension=="mp3").ToArray();if(selection.Length==0)return;Run(()=>{var w=new TagWindow(owner,store,selection);w.Closed+=(_,_)=>{engine.ReloadEditedJobs(selection.Select(j=>j.Id));Refresh(true);};w.Show();});}
    void Run(Action action){try{action();}catch(Exception e){status.Text=e.Message;}}
    void Play(DownloadJob j)=>Run(()=>{if(!File.Exists(j.FilePath))throw new FileNotFoundException(T("檔案已移動或刪除","File was moved or deleted"));Process.Start(new ProcessStartInfo(j.FilePath!){UseShellExecute=true});});
    public sealed class LibraryRow:INotifyPropertyChanged {public DownloadJob Job{get;}bool chosen;readonly Action<bool> change;public bool Exists=>File.Exists(Job.FilePath);public string Status=>Exists?T("✓ 已完成","✓ Completed"):T("檔案不存在","File missing");public bool Checked{get=>chosen;set{chosen=value;change(value);PropertyChanged?.Invoke(this,new(nameof(Checked)));}}public event PropertyChangedEventHandler? PropertyChanged;public LibraryRow(DownloadJob j,bool selected,Action<bool> change){Job=j;chosen=selected;this.change=change;}}
}
