using System.IO;
using System.Diagnostics;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Omni.Core;
using static Omni.Windows.UiKit;
namespace Omni.Windows;
public sealed class SettingsView:UserControl
{
    readonly Window owner;readonly Downloader engine;readonly Action saved;Preferences draft;
    readonly StackPanel form=new();readonly TextBlock status=Text("");readonly Dictionary<string,Action> readers=[];
    readonly StackPanel nav=new();int category;bool dirty;
    public Action? Back {get;set;}
    public Action<Preferences> StartupWriter {get;set;}=DesktopIntegration.ApplyStartup;
    public SettingsView(Window owner,Downloader engine,Action saved){this.owner=owner;this.engine=engine;this.saved=saved;draft=Json.Decode<Preferences>(Json.Encode(engine.Settings));Resources=owner.Resources;Build();}
    void Build(){var root=new DockPanel{Margin=new Thickness(18)};var title=new StackPanel{Margin=new Thickness(10,5,10,18)};var back=IconButton("back",T("返回主選單","Back to menu"),()=>Back?.Invoke());back.HorizontalAlignment=HorizontalAlignment.Left;title.Children.Add(back);title.Children.Add(Text(T("設定","Settings"),28));title.Children.Add(Text(T("自訂下載、格式與應用程式選項","Customize downloads, formats and application preferences"),14));DockPanel.SetDock(title,Dock.Top);root.Children.Add(title);
        var footer=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};footer.Children.Add(Button(T("還原此頁預設值","Reset this category"),ResetPage));footer.Children.Add(Button(T("儲存變更","Save changes"),()=>Save(),true));DockPanel.SetDock(footer,Dock.Bottom);root.Children.Add(footer);DockPanel.SetDock(status,Dock.Bottom);root.Children.Add(status);
        var sidebar=new Border{Child=nav,Width=230,Padding=new Thickness(0,8,16,8)};DockPanel.SetDock(sidebar,Dock.Left);root.Children.Add(sidebar);var names=new[]{T("一般","General"),T("下載","Downloads"),T("格式","Formats"),T("網絡","Network"),T("通知","Notifications"),T("關於","About")};var glyph=new[]{"settings","download","video","network","notification","info"};nav.Children.Clear();for(int i=0;i<names.Length;i++){int n=i;var item=IconButton(glyph[i],names[i],()=>{if(!ReadFields())return;category=n;Render();},category==i);item.MinHeight=58;item.FontSize=18;item.BorderThickness=new Thickness(0);item.HorizontalContentAlignment=HorizontalAlignment.Left;foreach(var text in ((StackPanel)item.Content).Children.OfType<TextBlock>())text.FontSize=18;nav.Children.Add(item);}
        var scroll=new ScrollViewer{Content=form,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled,Padding=new Thickness(12,0,12,10)};scroll.Resources[typeof(System.Windows.Controls.Primitives.ScrollBar)]=owner.FindResource("SlimScrollBar");root.Children.Add(scroll);Content=root;Render();Loaded+=(_,_)=>Typography(this,engine.Settings.TextScale);}
    string S(string zh,string en)=>T(zh,en);
    void Section(string zh,string en){form.Children.Add(new TextBlock{Text=T(zh,en),FontSize=20,FontWeight=FontWeights.SemiBold,Margin=new Thickness(8,20,8,8)});}
    void Note(string zh,string en){var t=Text(T(zh,en),12);t.SetResourceReference(TextBlock.ForegroundProperty,"Muted");t.Margin=new Thickness(10,3,10,10);form.Children.Add(t);}
    void Row(string label,FrameworkElement control){var grid=new Grid();grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1,GridUnitType.Star)});grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1.2,GridUnitType.Star)});var t=Text(label);t.Margin=new Thickness(0,0,16,0);grid.Children.Add(t);Grid.SetColumn(control,1);grid.Children.Add(control);var card=Card(grid,8);card.Margin=new Thickness(4,2,4,2);form.Children.Add(card);}
    PropertyInfo Prop(string key)=>typeof(Preferences).GetProperty(key)!;
    void Toggle(string key,string zh,string en){var c=new CheckBox{IsChecked=(bool)Prop(key).GetValue(draft)!,HorizontalAlignment=HorizontalAlignment.Right,Style=(Style)owner.FindResource("SettingsToggle")};c.Checked+=(_,_)=>dirty=true;c.Unchecked+=(_,_)=>dirty=true;readers[key]=()=>Prop(key).SetValue(draft,c.IsChecked==true);Row(T(zh,en),c);}
    void Field(string key,string zh,string en,bool number=false){var c=new TextBox{Text=Prop(key).GetValue(draft)?.ToString()??""};c.TextChanged+=(_,_)=>dirty=true;readers[key]=()=>{if(number){if(!int.TryParse(c.Text,out var n))throw new ArgumentException(T("請輸入整數：","Enter a whole number: ")+T(zh,en));Prop(key).SetValue(draft,n);}else Prop(key).SetValue(draft,c.Text.Trim());};Row(T(zh,en),c);}
    void Choice(string key,string zh,string en,(string value,string zh,string en)[] options){var c=new ComboBox{MinWidth=140};foreach(var v in options)c.Items.Add(new ComboBoxItem{Content=T(v.zh,v.en),Tag=v.value});c.SelectedIndex=Array.FindIndex(options,v=>v.value==(string)Prop(key).GetValue(draft)!);c.SelectionChanged+=(_,_)=>dirty=true;readers[key]=()=>Prop(key).SetValue(draft,((ComboBoxItem)c.SelectedItem).Tag.ToString());Row(T(zh,en),c);}
    void PathField(string key,string zh,string en,bool file=false){var panel=new DockPanel();var input=new TextBox{Text=Prop(key).GetValue(draft)?.ToString()??"",IsReadOnly=true,TextWrapping=TextWrapping.Wrap};var browse=Button(T("瀏覽","Browse"),()=>{if(file){var d=new Microsoft.Win32.OpenFileDialog{Filter="Netscape cookies|*.txt|All files|*.*"};if(d.ShowDialog(owner)==true){if(new FileInfo(d.FileName).Length>2_000_000||!File.ReadLines(d.FileName).Take(2).Any(s=>s.Contains("Cookie File")))throw new IOException("Invalid Netscape cookie file");input.Text=d.FileName;}}else {var d=new Microsoft.Win32.OpenFolderDialog();if(d.ShowDialog(owner)==true)input.Text=d.FolderName;}dirty=true;});DockPanel.SetDock(browse,Dock.Right);panel.Children.Add(browse);var clear=Button("×",()=>{input.Text="";dirty=true;});DockPanel.SetDock(clear,Dock.Right);panel.Children.Add(clear);panel.Children.Add(input);readers[key]=()=>Prop(key).SetValue(draft,input.Text);Row(T(zh,en),panel);}
    void Render(){readers.Clear();form.Children.Clear();status.Text="";foreach(var b in nav.Children.OfType<Button>())b.SetResourceReference(Control.BackgroundProperty,nav.Children.IndexOf(b)==category?"Accent":"Surface");
        switch(category){
        case 0:
            Section("外觀","Appearance");Choice("Theme","主題","Theme",[("dark","深色","Dark"),("light","淺色","Light"),("system","跟隨系統","System")]);Choice("Language","介面語言","Language",[("zh-Hant","繁體中文","繁體中文"),("en","English","English")]);
            NumberChoice("TextScale","文字大小 (%)","Text size (%)",[80,90,100,110,125,150]);NumberChoice("UiScale","介面大小 (%)","UI size (%)",[80,90,100,110,125,150]);Note("100% 為預設；儲存後即時套用。","100% is the default; applies after saving.");Section("應用程式","Application");Toggle("StartAtLogin","開機時自動啟動","Start at sign-in");Toggle("StartMinimized","啟動時縮至系統匣","Start in tray");Toggle("CloseToTray","關閉視窗後縮至系統匣","Close window to tray");Toggle("AutoUpdate","自動檢查更新","Automatically check for updates");Note("更新安裝及重開前會先徵求確認。最小化仍保留工作列。","Installation and restart require confirmation. Minimize keeps the taskbar button.");
            Section("下載偏好","Download preferences");Directories();Field("Concurrency","同時下載任務（1–10）","Concurrent tasks (1–10)",true);Toggle("Sound","完成提示音","Completion sound");Naming();break;
        case 1:
            Section("下載及儲存","Downloads and storage");Directories();Field("Concurrency","同時下載任務（1–10）","Concurrent tasks (1–10)",true);Field("LimitKiB","每個任務速度上限 KiB/s（0 = 不限）","Per-task KiB/s limit (0 = unlimited)",true);
            Choice("DuplicateAction","檔案重複時","Existing file",[("ask","詢問","Ask"),("overwrite","覆蓋","Overwrite"),("rename","自動重新命名","Auto rename"),("skip","跳過","Skip")]);Toggle("AutoRetry","下載失敗後自動重試","Retry failed downloads");Field("RetryCount","重試次數（0–20）","Retry count (0–20)",true);Field("RetrySeconds","重試間隔（秒）","Retry interval (seconds)",true);Toggle("ResumeOnStart","啟動後繼續未完成任務","Resume unfinished tasks at launch");Note("需要登入嘅任務重開後仍須由擴充功能重新傳送憑證。","Authenticated tasks need fresh credentials from the extension after restart.");
            Choice("CompletionAction","下載完成後","After completion",[("none","無操作","Do nothing"),("file","開啟檔案","Open file"),("folder","開啟資料夾","Open folder")]);Toggle("MonitorClipboard","監察剪貼簿影片連結","Watch clipboard for video links");Note("只在 App 前景讀取剪貼簿，填入連結；不會自動下載。","Only reads the clipboard while the app is foreground; fills the URL without downloading.");PathField("TempDirectory","暫存檔位置（空白使用預設）","Temporary folder (blank = default)");Toggle("CleanFailed","自動清理失敗任務暫存","Clean failed task temporary files");Note("取消／移除任務一律清理暫存；暫停保留續傳資料。","Removed tasks always clean temporary files; paused tasks keep resumable data.");break;
        case 2:
            Section("格式及品質","Formats and quality");Choice("DefaultType","預設下載類型","Default download type",[("video","影片","Video"),("audio","純音訊","Audio"),("ask","每次詢問","Ask each time")]);Choice("VideoFormat","影片格式","Video format",[("mp4","MP4","MP4"),("mkv","MKV","MKV"),("webm","WebM","WebM")]);NumberChoice("VideoHeight","影片畫質","Video quality",[0,2160,1440,1080,720]);Choice("AudioFormat","音訊格式","Audio format",[("mp3","MP3","MP3"),("m4a","M4A","M4A"),("flac","FLAC","FLAC"),("wav","WAV","WAV")]);NumberChoice("AudioKbps","音訊品質 kbps","Audio bitrate kbps",[128,192,256,320]);Note("位元率適用 MP3／M4A；FLAC／WAV 使用來源取樣率及聲道。轉成無損格式不會提升來源音質。","Bitrate applies to MP3/M4A. FLAC/WAV preserve source sampling and channels; conversion does not improve source quality.");Naming();
            var advanced=new StackPanel();var before=form.Children.Count;
            Section("編碼、字幕及中繼資料","Codec, subtitles and metadata");Choice("VideoCodec","影片編碼（來源篩選）","Video codec (source selection)",[("auto","自動","Auto"),("h264","H.264","H.264"),("h265","H.265","H.265"),("av1","AV1","AV1")]);Note("指定編碼無來源時會報錯，不會靜默換成另一編碼。","Unavailable source codecs produce an error instead of silently changing your choice.");Toggle("DownloadSubtitles","下載字幕（包括自動字幕）","Download subtitles (including automatic)");Field("SubtitleLanguages","字幕語言（逗號分隔）","Subtitle languages (comma separated)");Choice("SubtitleFormat","字幕格式","Subtitle format",[("srt","SRT","SRT"),("vtt","VTT","VTT")]);Toggle("EmbedSubtitles","將字幕嵌入影片","Embed subtitles");Toggle("KeepThumbnail","保留影片縮圖","Keep thumbnail file");Toggle("EmbedThumbnail","將縮圖嵌入音訊","Embed audio artwork");Toggle("KeepMetadata","保留標題、作者、日期等資料","Keep title, author and date metadata");Toggle("CleanTitle","自動清洗音樂標題後綴","Clean music title suffixes");Toggle("MusicBrainz","MusicBrainz 中繼資料配對","MusicBrainz metadata lookup");Note("啟用後會將歌曲名及歌手傳送 MusicBrainz；可靠配對先採用。MP3 第一封面仍用 YouTube 縮圖，手動編輯不被覆蓋。","Sends song and artist to MusicBrainz; only reliable matches apply. YouTube artwork stays first for MP3. Manual edits are preserved.");
            while(form.Children.Count>before){var child=form.Children[before];form.Children.RemoveAt(before);advanced.Children.Add(child);}form.Children.Add(new Expander{Header=T("進階設定","Advanced settings"),Content=advanced,Margin=new Thickness(8),IsExpanded=false});break;
        case 3:
            Section("連線","Connection");Choice("ProxyMode","代理伺服器","Proxy",[("off","關閉","Off"),("system","跟隨系統","System"),("custom","自訂","Custom")]);Field("ProxyUrl","代理網址（HTTP／SOCKS5）","Proxy URL (HTTP/SOCKS5)");Note("關閉代理不會繞過系統 VPN；如需直連，請在 VPN 設定 App.exe 及 yt-dlp.exe 分流。","Proxy Off does not bypass a system VPN. Configure split tunneling for App.exe and yt-dlp.exe in your VPN.");Field("TimeoutSeconds","下載逾時（5–600 秒）","Download timeout (5–600 seconds)",true);Field("ConnectionRetries","連線重試次數（0–20）","Connection retries (0–20)",true);Field("Fragments","每個任務分段連線（1–10）","Concurrent fragments per task (1–10)",true);Note("分段連線適用支援分段嘅 DASH／HLS 來源，並非任意檔案都可分段。","Fragment concurrency applies to supported DASH/HLS sources.");Choice("AllowedNetwork","只在指定網絡下載","Allowed network",[("any","任何網絡","Any"),("wifi","Wi-Fi","Wi-Fi"),("ethernet","有線網絡","Ethernet")]);Toggle("ScheduleLimit","速度限制排程","Scheduled rate limit");Field("LimitStart","開始時間 HH:mm","Start HH:mm");Field("LimitEnd","結束時間 HH:mm","End HH:mm");Field("ScheduledKiB","排程期間每任務 KiB/s","Scheduled per-task KiB/s",true);Note("跨越排程時會保留暫存並重新連線，套用新上限。","Tasks reconnect with their temporary data preserved when a rate schedule changes.");
            Section("瀏覽器及進階登入","Browser and advanced authentication");Field("ExtensionId","Chrome／Brave 擴充功能 ID","Chrome/Brave extension ID");form.Children.Add(Button(T("儲存並連接瀏覽器","Save and connect browser"),()=>{if(Save())try{RegistryIntegration.HealNativeHost(engine.Settings.ExtensionId);status.Text=T("已連接","Connected");}catch(Exception e){status.Text=e.Message;}}));PathField("CookieFile","自訂 Netscape Cookie 檔案","Custom Netscape cookie file",true);Note("Cookie 等同登入憑證。只選自己帳號嘅檔案，勿分享；只用於 YouTube 下載。路徑保存在本機設定，不会上傳 GitHub。","Cookies grant account access. Use only your own file and never share it. Used only for YouTube downloads; the local path is not uploaded to GitHub.");form.Children.Add(Button(T("清除網絡快取","Clear network cache"),()=>{try{engine.ClearNetworkCache();status.Text=T("快取已清除","Cache cleared");}catch(Exception e){status.Text=e.Message;}}));break;
        case 4:
            Section("通知","Notifications");Toggle("NotifyComplete","下載完成通知","Download complete");Toggle("NotifyFailure","下載失敗通知","Download failed");Toggle("NotifyAll","全部任務完成通知","All tasks finished");Toggle("SystemNotifications","顯示系統通知","Show system notifications");Toggle("Sound","播放提示音","Play notification sound");Choice("SoundName","通知音效","Notification sound",[("default","預設","Default"),("asterisk","提示","Asterisk"),("exclamation","提醒","Exclamation")]);form.Children.Add(Button(T("試播音效","Preview sound"),()=>{if(ReadFields())DesktopIntegration.PlaySound(draft);}));Toggle("TaskbarProgress","工作列進度","Taskbar progress");Toggle("QuietHours","勿擾時段","Quiet hours");Field("QuietStart","開始 HH:mm","Start HH:mm");Field("QuietEnd","結束 HH:mm","End HH:mm");break;
        case 5:
            Section("關於全能影音下載器","About Omni Downloader");Note("應用程式版本："+UpdateManager.CurrentVersion.ToString(3),"Application version: "+UpdateManager.CurrentVersion.ToString(3));Field("ReleaseRepository","GitHub 專案（owner/repository）","GitHub repository (owner/repository)");Toggle("AutoUpdate","自動檢查更新","Automatically check for updates");
            form.Children.Add(Button(T("檢查更新","Check for updates"),async()=>{try{if(ReadFields())status.Text=await UpdateManager.CheckStatus(draft.ReleaseRepository);}catch(Exception e){status.Text=e.Message;}}));form.Children.Add(Button(T("下載並安裝最新版本","Download and install latest"),async()=>{try{if(!Save()||!await new ConfirmWindow(owner,T("安裝更新","Install update"),T("將暫停任務、安裝更新並重開。設定及紀錄會保留。","Tasks will pause, then the app will update and restart. Settings and history are preserved."),T("下載並安裝","Download and install")).Ask())return;IsEnabled=false;await UpdateManager.DownloadAndLaunch(draft.ReleaseRepository,false,true,new Progress<string>(s=>status.Text=s));}catch(Exception e){status.Text=e.Message;}finally{IsEnabled=true;}},true));
            foreach(var (zh,en,suffix) in new[]{("更新紀錄","Changelog","/releases"),("使用說明","Help","#readme"),("支援與問題回報","Support and issues","/issues"),("私隱政策","Privacy policy","/blob/main/docs/PRIVACY.md"),("開源授權","Open source licenses","/blob/main/THIRD-PARTY.md")})form.Children.Add(Button(T(zh,en),()=>OpenRepository(suffix)));
            form.Children.Add(Button(T("開啟記錄檔資料夾","Open log folder"),()=>{var path=engine.LogDirectory;Directory.CreateDirectory(path);Process.Start(new ProcessStartInfo(path){UseShellExecute=true});}));
            var manual=new StackPanel();var hash=new TextBox();manual.Children.Add(Text(T("僅供手動更新：從可信發布頁取得 SHA256","Manual updates only: SHA256 from the trusted release"),12));manual.Children.Add(hash);var elevate=new CheckBox{Content=T("以管理員權限更新（目錄需要時）","Elevate only if the installation folder requires it")};manual.Children.Add(elevate);manual.Children.Add(Button(T("選擇已下載更新 ZIP","Select downloaded update ZIP"),async ()=>{try{if(!ReadFields())return;var d=new Microsoft.Win32.OpenFileDialog{Filter="ZIP|*.zip"};if(d.ShowDialog(owner)==true){UpdateManager.Launch(d.FileName,hash.Text.Trim(),$"https://github.com/{draft.ReleaseRepository}/releases",elevate.IsChecked==true,true);if(UpdateManager.ExitForUpdate is not null)await UpdateManager.ExitForUpdate();}}catch(Exception e){status.Text=e.Message;}}));form.Children.Add(new Expander{Header=T("手動更新（進階）","Manual update (advanced)"),Content=manual,Margin=new Thickness(10)});
            form.Children.Add(Button(T("恢復全部預設設定","Reset all preferences"),async()=>{if(await new ConfirmWindow(owner,T("恢復預設","Restore defaults"),T("只重設設定，保留下載紀錄及檔案；儲存變更後生效。","Reset preferences only. History and files are kept. Applies after Save changes."),T("還原","Reset")).Ask()){draft=new Preferences();dirty=true;Render();}}));break;
        }
        Dispatcher.BeginInvoke(()=>Typography(this,engine.Settings.TextScale),System.Windows.Threading.DispatcherPriority.Loaded);
    }
    void Directories(){PathField("Mp4Directory","預設影片儲存位置","Default video folder");PathField("Mp3Directory","預設音訊儲存位置","Default audio folder");}
    void NumberChoice(string key,string zh,string en,int[] values){var c=new ComboBox();foreach(int v in values)c.Items.Add(new ComboBoxItem{Content=v==0?T("最佳（最高 4K）","Best (up to 4K)"):v.ToString(),Tag=v});c.SelectedIndex=Array.IndexOf(values,(int)Prop(key).GetValue(draft)!);readers[key]=()=>Prop(key).SetValue(draft,(int)((ComboBoxItem)c.SelectedItem).Tag);c.SelectionChanged+=(_,_)=>dirty=true;Row(T(zh,en),c);}
    void Naming(){Field("VideoNaming","影片命名格式","Video filename template");Field("AudioNaming","音訊命名格式","Audio filename template");Note("支援 {title} {artist} {album} {quality} {date}；MP3 預設只有歌曲名。","Supports {title} {artist} {album} {quality} {date}. MP3 defaults to song title only.");var example=Text("",12);form.Children.Add(example);var timer=new System.Windows.Threading.DispatcherTimer{Interval=TimeSpan.FromMilliseconds(400)};timer.Tick+=(_,_)=>{try{foreach(var k in new[]{"VideoNaming","AudioNaming"})readers[k]();var j=new DownloadJob{Title=T("探索壯麗的自然風光","Explore the mountains"),Artist=T("歌手","Artist"),Height=draft.VideoHeight,AudioKbps=draft.AudioKbps};var v=DownloadOptions.FileStem(j,draft);j.Mode=DownloadMode.Mp3;j.Title=T("歌曲名","Song title");example.Text=T("即時範例：","Preview: ")+v+"."+draft.VideoFormat+" / "+DownloadOptions.FileStem(j,draft)+"."+draft.AudioFormat;}catch{}};timer.Start();example.Unloaded+=(_,_)=>timer.Stop();}
    bool ReadFields(){try{foreach(var f in readers.Values)f();return true;}catch(Exception e){status.Text=e.Message;return false;}}
    public bool Save(){if(!ReadFields())return false;try{var languageChanged=UiKit.Language!=draft.Language;draft.Validate();StartupWriter(draft);engine.SaveSettings(Json.Decode<Preferences>(Json.Encode(draft)));Apply(owner,draft);dirty=false;saved();if(languageChanged){if(form.Parent is ScrollViewer oldScroll)oldScroll.Content=null;if(status.Parent is Panel parent)parent.Children.Remove(status);if(nav.Parent is Border border)border.Child=null;Build();}status.Text=T("變更已儲存","Changes saved");return true;}catch(Exception e){status.Text=e.Message;return false;}}
    void ResetPage(){var defaults=new Preferences();foreach(var key in readers.Keys)Prop(key).SetValue(draft,Prop(key).GetValue(defaults));dirty=true;Render();}
    void OpenRepository(string suffix){if(!ReadFields())return;if(!System.Text.RegularExpressions.Regex.IsMatch(draft.ReleaseRepository,@"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")){status.Text=T("GitHub 專案格式錯誤","Invalid repository");return;}Process.Start(new ProcessStartInfo("https://github.com/"+draft.ReleaseRepository+suffix){UseShellExecute=true});}
    public async Task<bool> CanLeave()=>!dirty||await new ConfirmWindow(owner,T("未儲存變更","Unsaved changes"),T("離開並捨棄未儲存嘅設定？","Leave and discard unsaved changes?"),T("離開","Leave")).Ask();
}
