using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using Omni.Core;
using static Omni.Windows.UiKit;
namespace Omni.Windows;

public sealed class TagEditorView : UserControl
{
    readonly Window owner; readonly Store store; readonly Downloader engine;
    readonly Dictionary<string,ImageSource> thumbnails=[]; readonly List<DownloadJob> songs=[]; readonly HashSet<string> selected=[];
    readonly Dictionary<string,string> baseline=[]; readonly Dictionary<string,string> delta=[]; readonly Dictionary<string,TextBox> fields=[];
    readonly StackPanel songList=new(); readonly TextBox search=new(),raw=new(){Text="{}",AcceptsReturn=true,MinHeight=90};
    readonly TextBlock state=Text(""),error=Text(""),counter=Text(""),time=Text("0:00 / 0:00",12);
    readonly StackPanel noArtwork=new(){VerticalAlignment=VerticalAlignment.Center,HorizontalAlignment=HorizontalAlignment.Center};
    readonly Image artwork=new(){Width=220,Height=220,Stretch=Stretch.Uniform};
    readonly CheckBox rename=new(){Content=T("同時重新命名檔案","Also rename files"),IsChecked=false};
    readonly Button undoReview=Button("復原上次套用",()=>{}); TagReviewUndo? lastUndo; DownloadJob? undoSong;
    readonly Button save; readonly MediaPlayer player=new(); readonly Slider seek=new(){Minimum=0,Maximum=1},volume=new(){Minimum=0,Maximum=1,Value=.7};
    readonly DispatcherTimer playback=new(){Interval=TimeSpan.FromMilliseconds(300)};
    string? anchor; List<Cover>? covers; bool loading,busy,playing; DownloadJob? current;
    public bool Busy=>busy||loading;
    public bool Dirty=>delta.Count>0||raw.Text.Trim()!="{}"||covers is not null;
    public static readonly (string id,string zh,string en)[] Labels=[("TIT2","標題","Title"),("TPE1","演出者","Artist"),("TALB","專輯","Album"),("TPE2","專輯演出者","Album artist"),("TRCK","曲目","Track"),("TPOS","光碟","Disc"),("TYER","年份","Year"),("TCON","類型","Genre"),("TCOM","作曲者","Composer"),("COMM","註解","Comment")];
    public TagEditorView(Window owner,Downloader engine,Store store,DownloadJob[]? initial=null)
    {
        this.owner=owner;this.engine=engine;this.store=store;Resources=owner.Resources;
        songs.AddRange(store.Load(true).Where(j=>j.State==JobState.Completed&&j.Extension=="mp3"&&File.Exists(j.FilePath)));
        if(initial is not null)foreach(var j in initial){if(songs.All(x=>x.Id!=j.Id))songs.Add(j);selected.Add(j.Id);}
        SortSongs();
        var root=new DockPanel{Margin=new Thickness(18)};var top=new StackPanel();top.Children.Add(Text(T("標籤編輯","Tag editor"),28));top.Children.Add(Text(T("編輯 MP3 標題、演出者、專輯與封面資料","Edit MP3 song, artist, album and artwork"),14));
        var toolbar=new DockPanel{Margin=new Thickness(0,12,0,10)};
        toolbar.Children.Add(IconButton("add",T("加入 MP3","Add MP3"),()=>Pick(false),true));toolbar.Children.Add(IconButton("folder",T("加入資料夾","Add folder"),()=>Pick(true)));
        DockPanel.SetDock(counter,Dock.Right);toolbar.Children.Add(counter);toolbar.Children.Add(Hint(search,T("搜尋歌曲、演出者、專輯或檔名…","Search songs, artist, album or filename…")));top.Children.Add(toolbar);var selectionTools=new WrapPanel();selectionTools.Children.Add(Button(T("全選","Select all"),async()=>await SelectSongs(songs.Where(j=>HistorySearch.Matches(j,search.Text)).Select(j=>j.Id))));selectionTools.Children.Add(Button(T("取消全選","Clear selection"),async()=>await SelectSongs([])));selectionTools.Children.Add(IconButton("search",T("重新尋找封面","Find album artwork"),async()=>await FindArtwork()));selectionTools.Children.Add(IconButton("search","查找歌曲標籤",async()=>await FindMetadata(false)));selectionTools.Children.Add(IconButton("audio","Scan 音訊辨識",async()=>await FindMetadata(true)));top.Children.Add(selectionTools);DockPanel.SetDock(top,Dock.Top);root.Children.Add(top);
        var footer=new WrapPanel{HorizontalAlignment=HorizontalAlignment.Right};footer.Children.Add(rename);undoReview.Visibility=Visibility.Collapsed;undoReview.Click+=async(_,_)=>{if(lastUndo is null||undoSong is null)return;try{await lastUndo.Restore(store,undoSong);engine.ReloadEditedJobs([undoSong.Id]);await ReviewApplied(undoSong,[],null,null,0);error.Text="已復原上次標籤套用";undoReview.Visibility=Visibility.Collapsed;}catch(Exception e){error.Text=e.Message;}};footer.Children.Add(undoReview);footer.Children.Add(IconButton("back",T("復原變更","Revert changes"),()=>_=LoadSelection()));save=IconButton("save",T("儲存標籤","Save tags"),async()=>await Save(),true);save.Name="SaveTags";footer.Children.Add(save);DockPanel.SetDock(footer,Dock.Bottom);root.Children.Add(footer);error.Foreground=Brush("#FF7777");error.TextWrapping=TextWrapping.Wrap;DockPanel.SetDock(error,Dock.Bottom);root.Children.Add(error);
        var grid=new Grid();grid.ColumnDefinitions.Add(new(){Width=new GridLength(300)});grid.ColumnDefinitions.Add(new());
        var list=new ScrollViewer{Content=songList,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};list.Resources[typeof(System.Windows.Controls.Primitives.ScrollBar)]=owner.FindResource("SlimScrollBar");grid.Children.Add(Card(list,10));
        var editor=new StackPanel();var upper=new DockPanel();DockPanel.SetDock(state,Dock.Right);upper.Children.Add(state);upper.Children.Add(Text(T("歌曲資料","Song details"),22));editor.Children.Add(upper);
        var body=new Grid();body.RowDefinitions.Add(new(){Height=GridLength.Auto});body.RowDefinitions.Add(new(){Height=GridLength.Auto});body.ColumnDefinitions.Add(new(){Width=new GridLength(245)});body.ColumnDefinitions.Add(new());var art=new StackPanel{Margin=new Thickness(0,14,12,0)};var coverArea=new Grid{Width=220,Height=220,AllowDrop=true,Background=Brushes.Transparent};coverArea.DragOver+=(_,e)=>{e.Effects=selected.Count>0&&HasCoverData(e.Data)?DragDropEffects.Copy:DragDropEffects.None;e.Handled=true;};coverArea.Drop+=(_,e)=>{e.Handled=true;ReadCoverData(e.Data);};noArtwork.Children.Add(Icon("audio",44));noArtwork.Children.Add(Text(T("尚未加入封面","No artwork"),13));coverArea.Children.Add(noArtwork);coverArea.Children.Add(artwork);art.Children.Add(Card(coverArea,0));
        var artButtons=new WrapPanel();artButtons.Children.Add(IconButton("folder",T("更換封面","Change cover"),ChooseCover));artButtons.Children.Add(IconButton("delete",T("移除","Remove"),()=>{covers=[];SetArtwork(null);Changed();}));art.Children.Add(artButtons);art.Children.Add(Button(T("貼上剪貼簿封面","Paste artwork"),PasteCover));art.Children.Add(IconButton("play",T("播放／暫停","Play / Pause"),Play));art.Children.Add(seek);art.Children.Add(time);art.Children.Add(Text(T("音量","Volume"),12));art.Children.Add(volume);body.Children.Add(art);
        var form=new StackPanel{Margin=new Thickness(8),MaxWidth=440,HorizontalAlignment=HorizontalAlignment.Stretch};foreach(var (id,zh,en) in Labels){var row=new Grid();row.ColumnDefinitions.Add(new(){Width=new GridLength(85)});row.ColumnDefinitions.Add(new());row.ColumnDefinitions.Add(new(){Width=GridLength.Auto});row.Children.Add(Text(T(zh,en)));var f=new TextBox{MinWidth=0,MaxWidth=320,HorizontalAlignment=HorizontalAlignment.Stretch,HorizontalScrollBarVisibility=ScrollBarVisibility.Hidden,Padding=new Thickness(10,6,10,6),Name=id,AcceptsReturn=id=="COMM",MinHeight=id=="COMM"?75:40,TextWrapping=id=="COMM"?TextWrapping.Wrap:TextWrapping.NoWrap,Margin=new Thickness(2,4,2,4)};fields[id]=f;Grid.SetColumn(f,1);row.Children.Add(f);var clear=Button("×",()=>{f.Text="";delta[id]="";Changed();});clear.Padding=new Thickness(6);System.Windows.Automation.AutomationProperties.SetName(clear,T("清空","Clear ")+T(zh,en));Grid.SetColumn(clear,2);row.Children.Add(clear);form.Children.Add(row);f.TextChanged+=(_,_)=>{if(loading)return;if(baseline.GetValueOrDefault(id)==f.Text)delta.Remove(id);else delta[id]=f.Text;Changed();};}
        var more=new StackPanel();more.Children.Add(Text(T("自訂 ID3 Frame（Base64 JSON）；未改動嘅標籤會保留。","Custom ID3 frames (Base64 JSON); unchanged tags are preserved."),12));more.Children.Add(raw);form.Children.Add(new Expander{Header=T("更多標籤","More tags"),Content=more,Margin=new Thickness(2,12,2,0)});Grid.SetColumn(form,1);body.Children.Add(form);editor.Children.Add(body);
        body.SizeChanged+=(_,_)=>{var narrow=body.ActualWidth<650;body.ColumnDefinitions[0].Width=narrow?new GridLength(1,GridUnitType.Star):new GridLength(245);body.ColumnDefinitions[1].Width=narrow?new GridLength(0):new GridLength(1,GridUnitType.Star);Grid.SetColumn(form,narrow?0:1);Grid.SetRow(form,narrow?1:0);};var scroll=new ScrollViewer{Content=editor,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};scroll.Resources[typeof(System.Windows.Controls.Primitives.ScrollBar)]=owner.FindResource("SlimScrollBar");var card=Card(scroll,16);Grid.SetColumn(card,1);grid.Children.Add(card);root.Children.Add(grid);Content=root;
        rename.Checked+=(_,_)=>Changed();rename.Unchecked+=(_,_)=>Changed();AllowDrop=true;Drop+=async(_,e)=>{if(e.Data.GetData(DataFormats.FileDrop) is string[] paths)await Import(paths);};search.TextChanged+=(_,_)=>Rows();raw.TextChanged+=(_,_)=>{if(!loading)Changed();};volume.ValueChanged+=(_,_)=>player.Volume=volume.Value;
        seek.PreviewMouseLeftButtonUp+=(_,_)=>{if(player.NaturalDuration.HasTimeSpan)player.Position=TimeSpan.FromSeconds(seek.Value);};
        player.MediaFailed+=(_,e)=>error.Text=T("無法試聽：","Cannot preview: ")+e.ErrorException.Message;
        player.MediaEnded+=(_,_)=>{playing=false;player.Position=TimeSpan.Zero;};playback.Tick+=(_,_)=>{if(player.NaturalDuration.HasTimeSpan){seek.Maximum=Math.Max(1,player.NaturalDuration.TimeSpan.TotalSeconds);if(!seek.IsMouseCaptureWithin)seek.Value=player.Position.TotalSeconds;time.Text=$"{player.Position:m\\:ss} / {player.NaturalDuration.TimeSpan:m\\:ss}";}};
        Unloaded+=(_,_)=>{playback.Stop();player.Close();};Loaded+=(_,_)=>Typography(this,engine.Settings.TextScale);
        if(selected.Count==0&&songs.Count>0)selected.Add(songs[0].Id);Rows();_=LoadSelection();_=LoadThumbnails();
    }
    void SortSongs()=>songs.Sort((a,b)=>{
        static DateTimeOffset Date(DownloadJob song)=>song.CompletedAt??(song.FilePath is string path&&File.Exists(path)?new DateTimeOffset(File.GetLastWriteTimeUtc(path),TimeSpan.Zero):song.CreatedAt);
        var recent=Date(b).CompareTo(Date(a));return recent!=0?recent:string.Compare(a.Id,b.Id,StringComparison.Ordinal);
    });
    async Task LoadThumbnails(){foreach(var j in songs.ToArray()){try{var image=await Task.Run(()=>{var bytes=Id3Document.Read(j.FilePath!).GetCovers().FirstOrDefault()?.Bytes;if(bytes is null)return null;using var stream=new MemoryStream(bytes);var bm=new BitmapImage();bm.BeginInit();bm.CacheOption=BitmapCacheOption.OnLoad;bm.DecodePixelWidth=128;bm.StreamSource=stream;bm.EndInit();bm.Freeze();return bm;});if(image is not null)thumbnails[j.Id]=image;}catch{}}Rows();}
    void Changed(bool keepError=false){var invalid=rename.IsChecked==true&&delta.TryGetValue("TIT2",out var title)?Omni.Core.Validation.TitleError(title):null;if(!keepError)error.Text=invalid??"";state.Text=Dirty?T("● 尚未儲存","● Unsaved"):T("已儲存","Saved");save.IsEnabled=!busy&&selected.Count>0&&Dirty&&invalid is null;}
    void Rows(){Dispatcher.BeginInvoke(()=>Typography(this,engine.Settings.TextScale),System.Windows.Threading.DispatcherPriority.Loaded);songList.Children.Clear();counter.Text=T($"已選取 {selected.Count} 首歌曲",$"{selected.Count} songs selected");foreach(var j in songs.Where(j=>HistorySearch.Matches(j,search.Text))){var row=new DockPanel{Margin=new Thickness(4,10,4,10)};var check=new CheckBox{IsChecked=selected.Contains(j.Id),Visibility=selected.Count>=2?Visibility.Visible:Visibility.Collapsed};row.Children.Add(check);var thumb=new Image{Width=54,Height=54,Margin=new Thickness(5,0,10,0),Stretch=Stretch.Uniform};try{if(thumbnails.TryGetValue(j.Id,out var image))thumb.Source=image;else if(j.Thumbnail is not null)thumb.Source=new BitmapImage(new Uri(j.Thumbnail));}catch{}row.Children.Add(thumb);var t=new StackPanel();t.Children.Add(Text(j.Title,16));t.Children.Add(Text(j.Artist+" · MP3",12));row.Children.Add(t);var c=Card(row,5);if(selected.Contains(j.Id))c.SetResourceReference(Border.BackgroundProperty,"Selected");songList.Children.Add(c);c.MouseLeftButtonUp+=async(_,e)=>{if(e.Handled)return;e.Handled=true;var keys=System.Windows.Input.Keyboard.Modifiers;var next=new HashSet<string>();if(keys.HasFlag(System.Windows.Input.ModifierKeys.Shift)&&anchor is not null){var ids=songs.Where(x=>HistorySearch.Matches(x,search.Text)).Select(x=>x.Id).ToList();int a=ids.IndexOf(anchor),b=ids.IndexOf(j.Id);if(a>=0)next.UnionWith(ids.Skip(Math.Min(a,b)).Take(Math.Abs(a-b)+1));else next.Add(j.Id);}else if(keys.HasFlag(System.Windows.Input.ModifierKeys.Control)){next.UnionWith(selected);if(!next.Add(j.Id))next.Remove(j.Id);anchor=j.Id;}else{next.Add(j.Id);anchor=j.Id;}await SelectSongs(next);};check.Click+=async(_,_)=>{var value=check.IsChecked==true;if(!await CanLeave()){Rows();return;}if(value)selected.Add(j.Id);else selected.Remove(j.Id);Rows();_=LoadSelection();};}songList.Children.Add(Text(T("拖放 MP3 檔案或資料夾至此","Drop MP3 files or folders here"),13));}
    async Task SelectSongs(IEnumerable<string> ids){var next=ids.ToArray();if(!await CanLeave())return;selected.Clear();selected.UnionWith(next);Rows();await LoadSelection();}
    public async Task ReviewApplied(DownloadJob song,Dictionary<string,string> applied,Cover? cover,TagReviewUndo? undo,int count){
        var draft=delta.Where(p=>!applied.ContainsKey(p.Key)).ToDictionary(p=>p.Key,p=>p.Value);var extra=raw.Text;var draftCover=covers;
        thumbnails.Remove(song.Id);await LoadSelection();loading=true;try{foreach(var (id,value) in draft){delta[id]=value;if(fields.TryGetValue(id,out var field))field.Text=value;}raw.Text=extra;if(cover is null&&draftCover is not null){covers=draftCover;SetArtwork(covers.FirstOrDefault()?.Bytes);}}finally{loading=false;}
        lastUndo=undo;undoSong=song;undoReview.Visibility=undo is null?Visibility.Collapsed:Visibility.Visible;error.Text=$"已套用 {count} 個標籤變更";Changed(true);_=LoadThumbnails();
    }
    async Task FindMetadata(bool scan){
        if(scan){if(Busy)return;if(selected.Count!=1){error.Text="請先選擇一首 MP3 再 Scan 音訊辨識。";return;}if(owner is MainWindow main)main.OpenAcoustIdReview(this,songs.First(j=>selected.Contains(j.Id)));return;}
        if(selected.Count!=1){error.Text="請選擇一首歌曲預覽配對；封面修改仍支援多選。";return;}if(!await CanLeave())return;
        busy=true;IsEnabled=false;try{var song=songs.First(j=>selected.Contains(j.Id));var service=new MusicMetadata();using var timeout=new CancellationTokenSource(TimeSpan.FromSeconds(100));
            MusicLookup result;
            if(scan)result=await service.Scan(song.FilePath!,engine.FfmpegPath,engine.Settings.AcoustIdClientKey,song.Duration,timeout.Token);
            else{var input=await new MusicSearchWindow(owner,song.Title,song.Artist).Ask();if(input is null)return;using var lookupTimeout=new CancellationTokenSource(TimeSpan.FromSeconds(60));if(MusicMetadata.TryRecordingId(input.Value.Title,out var recordingId))result=await service.Recording(recordingId.ToString(),null,lookupTimeout.Token);else{var choices=await service.SearchChoices(input.Value.Title,input.Value.Artist,song.Duration,lookupTimeout.Token);if(choices.Length==0){error.Text="MusicBrainz：查無結果，可嘗試 Scan 音訊辨識。";return;}result=new(MusicLookupState.Ambiguous,Choices:choices);}}
            if(result.Choices is {Length:>0} candidates){var choice=await new MusicMatchWindow(owner,candidates).Ask();if(choice is null)return;using var resolveTimeout=new CancellationTokenSource(TimeSpan.FromSeconds(60));result=await service.Recording(choice.RecordingId,choice.ReleaseId,resolveTimeout.Token);}
            if(result.State is not (MusicLookupState.Matched or MusicLookupState.MatchedNoCover)){error.Text=result.Message;return;}
            await LoadSelection();var values=result.Tags??new Dictionary<string,string>{{"TIT2",result.Title??song.Title},{"TPE1",result.Artist??song.Artist},{"TALB",result.Album??song.Album}};
            foreach(var (key,value) in values)if(fields.TryGetValue(key,out var field))field.Text=value;
            if(result.Cover is not null&&!song.CoverUserEdited&&!song.IsUserEdited)AcceptCover(result.Cover.Bytes);
            error.Text="已載入配對預覽，請核對資料後按「儲存標籤」。手動封面會保留。";
        }catch(Exception ex){error.Text="配對未完成："+ex.Message;}finally{busy=false;IsEnabled=true;Changed(true);}
    }
    async Task FindArtwork(){if(selected.Count==0||!await CanLeave())return;busy=true;IsEnabled=false;player.Close();int found=0,missing=0,skipped=0,failed=0;try{var persisted=store.Load().Select(j=>j.Id).ToHashSet();foreach(var j in songs.Where(j=>selected.Contains(j.Id))){try{var doc=await Task.Run(()=>Id3Document.Read(j.FilePath!));if(j.CoverUserEdited||doc.GetCovers().Any(c=>c.Description=="User cover")||doc.GetCovers().Count>0&&(j.IsUserEdited||string.IsNullOrEmpty(j.Url))){skipped++;continue;}Cover? art=null;if(Uri.TryCreate(j.Url,UriKind.Absolute,out _))try{using var timeout=new CancellationTokenSource(TimeSpan.FromSeconds(45));art=await engine.FindSourceArtwork(j.Url,await engine.Analyze(j.Url,ct:timeout.Token),ct:timeout.Token);}catch(Exception ex)when(ex is not OutOfMemoryException){}if(art is null)art=(await new MusicMetadata().Lookup(j.Title,j.Artist,j.Duration,CancellationToken.None)).Cover;if(art is null||!AlbumArtwork.Accept(art.Bytes)){missing++;continue;}await new TagEditor(store).Apply([j],new([],Covers:[art],RenameFile:false),persisted.Contains(j.Id),automaticCover:true);found++;}catch{failed++;}}engine.ReloadEditedJobs(persisted);await LoadSelection();await LoadThumbnails();error.Text=T($"封面：更新 {found}、未找到 {missing}、保留手動封面 {skipped}、失敗 {failed}",$"Artwork: {found} updated, {missing} not found, {skipped} protected, {failed} failed");}finally{busy=false;IsEnabled=true;}}
    async Task LoadSelection(){loading=true;IsEnabled=false;error.Text="";try{player.Close();playing=false;playback.Stop();delta.Clear();covers=null;raw.Text="{}";current=songs.FirstOrDefault(j=>selected.Contains(j.Id));var paths=songs.Where(j=>selected.Contains(j.Id)).Select(j=>j.FilePath!).ToArray();var docs=await Task.Run(()=>paths.Select(Id3Document.Read).ToArray());foreach(var (id,f) in fields){var vals=docs.Select(d=>d.Text(id=="TYER"&&d.Version==4?"TDRC":id)).Distinct().ToArray();f.Text=vals.Length==1?vals[0]:"";baseline[id]=f.Text;f.ToolTip=vals.Length>1?T("多個值；留空不會修改","Multiple values; untouched fields are preserved"):null;}SetArtwork(docs.FirstOrDefault()?.GetCovers().FirstOrDefault()?.Bytes);state.Text=docs.Length>1?T("多選：只套用有修改嘅欄位","Multiple songs: only changed fields apply"):"";}catch(Exception e){error.Text=e.Message;}finally{loading=false;IsEnabled=true;Changed(true);}}
    void SetArtwork(byte[]? bytes){noArtwork.Visibility=bytes is null?Visibility.Visible:Visibility.Collapsed;artwork.Source=null;if(bytes is null)return;using var stream=new MemoryStream(bytes);var image=new BitmapImage();image.BeginInit();image.CacheOption=BitmapCacheOption.OnLoad;image.StreamSource=stream;image.EndInit();image.Freeze();artwork.Source=image;}
    void AcceptCover(byte[] bytes){if(selected.Count==0)throw new IOException("請先選擇歌曲");if(bytes.Length>32*1024*1024)throw new IOException("封面不可超過 32 MB");using var input=new MemoryStream(bytes);var decoder=BitmapDecoder.Create(input,BitmapCreateOptions.PreservePixelFormat,BitmapCacheOption.OnLoad);var frame=decoder.Frames[0];if(!AlbumArtwork.NearSquare(frame.PixelWidth,frame.PixelHeight))throw new IOException("請選擇近正方形專輯封面；圖片不會自動裁切或拉伸。");var mime=decoder is JpegBitmapDecoder?"image/jpeg":"image/png";if(mime=="image/png"&&decoder is not PngBitmapDecoder){var encoder=new PngBitmapEncoder();encoder.Frames.Add(frame);using var output=new MemoryStream();encoder.Save(output);bytes=output.ToArray();}SetArtwork(bytes);covers=[new(bytes,mime,"User cover",3)];Changed();}
    static bool ImagePath(string path)=>File.Exists(path)&&new[]{".png",".jpg",".jpeg",".bmp",".gif",".tif",".tiff"}.Contains(Path.GetExtension(path).ToLowerInvariant());
    static bool HasCoverData(System.Windows.IDataObject data)=>data.GetDataPresent(DataFormats.FileDrop)||data.GetDataPresent(DataFormats.Bitmap)||data.GetDataPresent("PNG")||data.GetDataPresent(DataFormats.UnicodeText);
    void ReadCoverData(System.Windows.IDataObject data){try{
        if(selected.Count==0)throw new IOException("請先選擇歌曲");
        var files=data.GetData(DataFormats.FileDrop) as string[];var path=files?.FirstOrDefault(ImagePath);
        if(path is null&&data.GetData(DataFormats.UnicodeText) is string text){text=text.Trim().Trim('"');if(Uri.TryCreate(text,UriKind.Absolute,out var uri)&&uri.IsFile)text=uri.LocalPath;if(ImagePath(text))path=text;}
        if(path is not null){if(new FileInfo(path).Length>32*1024*1024)throw new IOException("封面不可超過 32 MB");AcceptCover(File.ReadAllBytes(path));return;}
        var png=data.GetData("PNG");if(png is Stream stream){using var output=new MemoryStream();var buffer=new byte[8192];int n;while((n=stream.Read(buffer,0,buffer.Length))>0){if(output.Length+n>32*1024*1024)throw new IOException("封面不可超過 32 MB");output.Write(buffer,0,n);}AcceptCover(output.ToArray());return;}if(png is byte[] bytes){AcceptCover(bytes);return;}
        if(data.GetData(DataFormats.Bitmap) is BitmapSource image){var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(image));using var output=new MemoryStream();encoder.Save(output);AcceptCover(output.ToArray());return;}
        error.Text="剪貼簿或拖放內容沒有可用圖片。請複製圖片本身或圖片檔案，再重試。";
    }catch(Exception e){error.Text=e.Message;}}
    void ChooseCover(){try{var d=new Microsoft.Win32.OpenFileDialog{Filter="Images|*.jpg;*.jpeg;*.png;*.bmp;*.gif;*.tif;*.tiff"};if(d.ShowDialog(owner)==true){var data=new System.Windows.DataObject(DataFormats.FileDrop,new[]{d.FileName});ReadCoverData(data);}}catch(Exception e){error.Text=e.Message;}}
    async void PasteCover(){for(int attempt=0;attempt<3;attempt++)try{var data=System.Windows.Clipboard.GetDataObject();if(data is null)error.Text="剪貼簿沒有圖片。請先複製圖片或圖片檔案。";else ReadCoverData(data);return;}catch(System.Runtime.InteropServices.COMException){if(attempt==2)error.Text="剪貼簿暫時被其他程式佔用，請稍後再試。";else await Task.Delay(100);}catch(Exception e){error.Text=e.Message;return;}}
    void Play(){try{if(current?.FilePath is null)return;if(player.Source is null){player.Open(new Uri(current.FilePath));player.Volume=volume.Value;}if(playing)player.Pause();else player.Play();playing=!playing;playback.Start();}catch(Exception e){error.Text=e.Message;}}
    async void Pick(bool folder){if(folder){var d=new Microsoft.Win32.OpenFolderDialog();if(d.ShowDialog(owner)==true)await Import([d.FolderName]);}else{var d=new Microsoft.Win32.OpenFileDialog{Filter="MP3|*.mp3",Multiselect=true};if(d.ShowDialog(owner)==true)await Import(d.FileNames);}}
    public async Task Import(IEnumerable<string> paths){if(!await CanLeave())return;try{var imported=await Task.Run(()=>{var files=paths.SelectMany(p=>Directory.Exists(p)?Directory.EnumerateFiles(p,"*.mp3",new EnumerationOptions{RecurseSubdirectories=true,IgnoreInaccessible=true,AttributesToSkip=FileAttributes.ReparsePoint}):new[]{p});return files.Where(p=>Path.GetExtension(p).Equals(".mp3",StringComparison.OrdinalIgnoreCase)).Select(p=>{var d=Id3Document.Read(p);return new DownloadJob{FilePath=Path.GetFullPath(p),Title=string.IsNullOrEmpty(d.Text("TIT2"))?Path.GetFileNameWithoutExtension(p):d.Text("TIT2"),Artist=d.Text("TPE1"),Album=d.Text("TALB"),Mode=DownloadMode.Mp3,OutputFormat="mp3",State=JobState.Completed,CompletedAt=new DateTimeOffset(File.GetLastWriteTimeUtc(p),TimeSpan.Zero)};}).ToArray();});foreach(var j in imported)if(songs.All(x=>!string.Equals(x.FilePath,j.FilePath,StringComparison.OrdinalIgnoreCase)))songs.Add(j);SortSongs();selected.Clear();foreach(var j in songs.Where(j=>imported.Any(x=>x.FilePath==j.FilePath)))selected.Add(j.Id);Rows();await LoadSelection();_=LoadThumbnails();}catch(Exception e){error.Text=T("加入失敗：","Import failed: ")+e.Message;}}
    public async Task<bool> CanLeave()=>!Busy&&(!Dirty||await new ConfirmWindow(owner,T("未儲存變更","Unsaved changes"),T("離開並捨棄未儲存嘅標籤變更？","Leave and discard tag changes?"),T("捨棄變更","Discard changes")).Ask());
    async Task Save(){if(Busy||!Dirty)return;player.Close();playing=false;playback.Stop();busy=true;IsEnabled=false;try{var rawFields=Json.Decode<Dictionary<string,string>>(raw.Text);var rows=songs.Where(j=>selected.Contains(j.Id)).ToArray();var persisted=store.Load().Select(j=>j.Id).ToHashSet();var changes=new Dictionary<string,string>(delta);var newCovers=covers;var shouldRename=rename.IsChecked==true;await Task.Run(async()=>{foreach(var j in rows){var d=Id3Document.Read(j.FilePath!);var values=new Dictionary<string,string>(changes);if(d.Version==4&&values.Remove("TYER",out var year))values["TDRC"]=year;await new TagEditor(store).Apply([j],new(values,rawFields,newCovers,shouldRename),persisted.Contains(j.Id));}});engine.ReloadEditedJobs(rows.Where(j=>persisted.Contains(j.Id)).Select(j=>j.Id));Rows();await LoadSelection();_=LoadThumbnails();}catch(Exception e){error.Text=T("未能完成儲存：","Could not finish saving: ")+e.Message;}finally{busy=false;IsEnabled=true;Changed(true);}}
}
